export const encouragements = [
    {   id: 4,
        message: "¡Buen Trabajo!",
    },
    {   id: 9,
        message: "¡Sigue así!",
    },
    {   id: 13,
        message: "¡No te rindas!",
    },
    {   id: 19,
        message: "¡Terminaste la etapa 1!",
    },
    {   id: 22,
        message: "¡Estás a mitad de camino!",
    },
    {   id: 25,
        message: "¡Vas muy bien!",
    },
    {   id: 31,
        message: "¡Terminaste la etapa 2!",
    },
    {   id: 37,
        message: "¡Sí se puede!",
    },
    {   id: 39,
        message: "¡Estás tan cerca!",
    },
];