export const quiz = {
  totalQuestions: 5,
  questions: [
    {
      id: 1,
      question: 'Creo que mis compañeros deberían respetar mis especialidades.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Paris',
    },
    {
      id: 2,
      question: 'Intento solucionar problemas al encontrarlos.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Jupiter',
    },
    {
      id: 3,
      question: 'Tengo facilidad comunicándome con los demás.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Vatican City',
    },
    {
      id: 4,
      question: 'Presto atención a lo que pasa a mi alrededor.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Mandarin',
    },
    {
      id: 5,
      question: 'En equipos, me importa hacer las cosas bien.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 6,
      question: 'Me gusta tener una rutina diaria.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 7,
      question: 'Tengo una manera de mantener mi horario.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 8,
      question: 'Puedo solucionar problemas y llegar a conclusiones.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 9,
      question: 'Puedo manejar situaciones, aunque no tenga toda la información.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 10,
      question: 'Puedo cambiar mi forma de hablar dependiendo de la situación.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 11,
      question: 'Me gusta asegurarme que estoy en camino de alcanzar mis objetivos con los demás.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 12,
      question: 'Me gusta planear y organizar cosas con otra gente.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 13,
      question: 'Puedo explicar mis pensamientos de manera lógica y convincente.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 14,
      question: 'Considero situaciones difíciles como oportunidades para aprender y crecer.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 15,
      question: 'Puedo cambiar mi forma de hablar dependiendo de la situación.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 16,
      question: 'Logro las metas que me propongo.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 17,
      question: 'Me aseguro de acabar mis tareas a tiempo.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 18,
      question: 'Mi trabajo es parte de mi identidad.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 19,
      question: 'Me doy tiempo para completar mis tareas.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 20,
      question: 'En grupos, intento trabajar de manera justa.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 21,
      question: 'Me gusta averiguar como funcionan las cosas.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 22,
      question: 'Soy capaz de superar dificultades del día a día.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 23,
      question: 'Celebro cuando mis equipos lo hacen bien.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 24,
      question: 'Soy capaz de tener prioridades.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 25,
      question: 'Soy bueno gestionando mi tiempo.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 26,
      question: 'En las discusiones, escucho lo que todos tienen que decir y respeto sus opiniones.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 27,
      question: 'Soy alguien relajado y no tengo dificultad para hablar en público.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 28,
      question: 'Me encargo de tareas extras cuando puedo.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 29,
      question: 'Antes de decidir algo, hablo con gente para saber lo que opinan.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 30,
      question: "Tomo decisiones dependiendo de mis sentimientos y los de los demás.",
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 31,
      question: 'Presto atención al hablar con alguien.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 32,
      question: 'Presto atención y escucho cuando alguien habla.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 33,
      question: 'Si veo que algo se está haciendo mal, lo denunciaría a la autoridad correspondiente.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 34,
      question: 'Me gusta solucionar problemas complicados.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 35,
      question: "Siempre soy puntual al quedar con gente.",
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 36,
      question: 'Tengo control de mis emociones para evitar que las situaciones empeoren.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 37,
      question: 'Me parece interesante aprender cosas nuevas.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 38,
      question: 'Si alguien comete algún error, no me cuesta decírselo.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 39,
      question: 'Me gusta aprender cosas nuevas.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 40,
      question: 'Mantengo mi mentalidad abierta al hablar con alguien.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 41,
      question: 'Estoy seguro que soy capaz de tener un efecto positivo en cualquier situación.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
    {
      id: 42,
      question: 'Tengo esperanza hasta en situaciones difíciles.',
      answers: ['Muy de acuerdo', 'De acuerdo', 'Neutral', 'En desacuerdo', 'Muy de desacuerdo'],
      correctAnswer: 'Trapp',
    },
  ],
};
